/*
 * generated by Xtext 2.11.0
 */
package org.etl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SparrowStandaloneSetup extends SparrowStandaloneSetupGenerated {

	def static void doSetup() {
		new SparrowStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
