/**
 * generated by Xtext 2.11.0
 */
package org.etl.ide;

import org.etl.ide.AbstractSparrowIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SparrowIdeModule extends AbstractSparrowIdeModule {
}
