/**
 * generated by Xtext 2.11.0
 */
package org.etl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.etl.SparrowRuntimeModule;
import org.etl.SparrowStandaloneSetup;
import org.etl.ide.SparrowIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SparrowIdeSetup extends SparrowStandaloneSetup {
  @Override
  public Injector createInjector() {
    SparrowRuntimeModule _sparrowRuntimeModule = new SparrowRuntimeModule();
    SparrowIdeModule _sparrowIdeModule = new SparrowIdeModule();
    return Guice.createInjector(Modules2.mixin(_sparrowRuntimeModule, _sparrowIdeModule));
  }
}
