/**
 * generated by Xtext 2.12.0
 */
package org.etl.sparrow.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.etl.sparrow.ClickSendSms;
import org.etl.sparrow.SparrowPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Click Send Sms</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.etl.sparrow.impl.ClickSendSmsImpl#getUserid <em>Userid</em>}</li>
 *   <li>{@link org.etl.sparrow.impl.ClickSendSmsImpl#getSecurityKey <em>Security Key</em>}</li>
 *   <li>{@link org.etl.sparrow.impl.ClickSendSmsImpl#getTarget <em>Target</em>}</li>
 *   <li>{@link org.etl.sparrow.impl.ClickSendSmsImpl#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClickSendSmsImpl extends ActionImpl implements ClickSendSms
{
  /**
   * The default value of the '{@link #getUserid() <em>Userid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUserid()
   * @generated
   * @ordered
   */
  protected static final String USERID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUserid() <em>Userid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUserid()
   * @generated
   * @ordered
   */
  protected String userid = USERID_EDEFAULT;

  /**
   * The default value of the '{@link #getSecurityKey() <em>Security Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecurityKey()
   * @generated
   * @ordered
   */
  protected static final String SECURITY_KEY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSecurityKey() <em>Security Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecurityKey()
   * @generated
   * @ordered
   */
  protected String securityKey = SECURITY_KEY_EDEFAULT;

  /**
   * The default value of the '{@link #getTarget() <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected static final String TARGET_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTarget() <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected String target = TARGET_EDEFAULT;

  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final String VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected String value = VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClickSendSmsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SparrowPackage.Literals.CLICK_SEND_SMS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getUserid()
  {
    return userid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUserid(String newUserid)
  {
    String oldUserid = userid;
    userid = newUserid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SparrowPackage.CLICK_SEND_SMS__USERID, oldUserid, userid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSecurityKey()
  {
    return securityKey;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSecurityKey(String newSecurityKey)
  {
    String oldSecurityKey = securityKey;
    securityKey = newSecurityKey;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SparrowPackage.CLICK_SEND_SMS__SECURITY_KEY, oldSecurityKey, securityKey));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTarget()
  {
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTarget(String newTarget)
  {
    String oldTarget = target;
    target = newTarget;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SparrowPackage.CLICK_SEND_SMS__TARGET, oldTarget, target));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(String newValue)
  {
    String oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SparrowPackage.CLICK_SEND_SMS__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SparrowPackage.CLICK_SEND_SMS__USERID:
        return getUserid();
      case SparrowPackage.CLICK_SEND_SMS__SECURITY_KEY:
        return getSecurityKey();
      case SparrowPackage.CLICK_SEND_SMS__TARGET:
        return getTarget();
      case SparrowPackage.CLICK_SEND_SMS__VALUE:
        return getValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SparrowPackage.CLICK_SEND_SMS__USERID:
        setUserid((String)newValue);
        return;
      case SparrowPackage.CLICK_SEND_SMS__SECURITY_KEY:
        setSecurityKey((String)newValue);
        return;
      case SparrowPackage.CLICK_SEND_SMS__TARGET:
        setTarget((String)newValue);
        return;
      case SparrowPackage.CLICK_SEND_SMS__VALUE:
        setValue((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SparrowPackage.CLICK_SEND_SMS__USERID:
        setUserid(USERID_EDEFAULT);
        return;
      case SparrowPackage.CLICK_SEND_SMS__SECURITY_KEY:
        setSecurityKey(SECURITY_KEY_EDEFAULT);
        return;
      case SparrowPackage.CLICK_SEND_SMS__TARGET:
        setTarget(TARGET_EDEFAULT);
        return;
      case SparrowPackage.CLICK_SEND_SMS__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SparrowPackage.CLICK_SEND_SMS__USERID:
        return USERID_EDEFAULT == null ? userid != null : !USERID_EDEFAULT.equals(userid);
      case SparrowPackage.CLICK_SEND_SMS__SECURITY_KEY:
        return SECURITY_KEY_EDEFAULT == null ? securityKey != null : !SECURITY_KEY_EDEFAULT.equals(securityKey);
      case SparrowPackage.CLICK_SEND_SMS__TARGET:
        return TARGET_EDEFAULT == null ? target != null : !TARGET_EDEFAULT.equals(target);
      case SparrowPackage.CLICK_SEND_SMS__VALUE:
        return VALUE_EDEFAULT == null ? value != null : !VALUE_EDEFAULT.equals(value);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (userid: ");
    result.append(userid);
    result.append(", securityKey: ");
    result.append(securityKey);
    result.append(", target: ");
    result.append(target);
    result.append(", value: ");
    result.append(value);
    result.append(')');
    return result.toString();
  }

} //ClickSendSmsImpl
