/*
 * generated by Xtext
 */
package org.etl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SparrowUiModule extends org.etl.ui.AbstractSparrowUiModule {
	public SparrowUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
