/*
 * generated by Xtext 2.12.0
 */
package org.etl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.etl.ide.contentassist.antlr.internal.InternalSparrowParser;
import org.etl.services.SparrowGrammarAccess;

public class SparrowParser extends AbstractContentAssistParser {

	@Inject
	private SparrowGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalSparrowParser createParser() {
		InternalSparrowParser result = new InternalSparrowParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
					put(grammarAccess.getOperatorAccess().getAlternatives(), "rule__Operator__Alternatives");
					put(grammarAccess.getProcessAccess().getGroup(), "rule__Process__Group__0");
					put(grammarAccess.getTryAccess().getGroup(), "rule__Try__Group__0");
					put(grammarAccess.getFinallyAccess().getGroup(), "rule__Finally__Group__0");
					put(grammarAccess.getCatchAccess().getGroup(), "rule__Catch__Group__0");
					put(grammarAccess.getFBCLeadAccess().getGroup(), "rule__FBCLead__Group__0");
					put(grammarAccess.getDropfileAccess().getGroup(), "rule__Dropfile__Group__0");
					put(grammarAccess.getDoozleAccess().getGroup(), "rule__Doozle__Group__0");
					put(grammarAccess.getRestAccess().getGroup(), "rule__Rest__Group__0");
					put(grammarAccess.getRestPartAccess().getGroup(), "rule__RestPart__Group__0");
					put(grammarAccess.getTrelloGETAccess().getGroup(), "rule__TrelloGET__Group__0");
					put(grammarAccess.getTrelloPUTAccess().getGroup(), "rule__TrelloPUT__Group__0");
					put(grammarAccess.getFetchAccess().getGroup(), "rule__Fetch__Group__0");
					put(grammarAccess.getCallprocessAccess().getGroup(), "rule__Callprocess__Group__0");
					put(grammarAccess.getUpdatedauditAccess().getGroup(), "rule__Updatedaudit__Group__0");
					put(grammarAccess.getSmsAccess().getGroup(), "rule__Sms__Group__0");
					put(grammarAccess.getSlackPUTAccess().getGroup(), "rule__SlackPUT__Group__0");
					put(grammarAccess.getGooglecalPUTAccess().getGroup(), "rule__GooglecalPUT__Group__0");
					put(grammarAccess.getCopydataAccess().getGroup(), "rule__Copydata__Group__0");
					put(grammarAccess.getWriteCsvAccess().getGroup(), "rule__WriteCsv__Group__0");
					put(grammarAccess.getLoadCsvAccess().getGroup(), "rule__LoadCsv__Group__0");
					put(grammarAccess.getTransformAccess().getGroup(), "rule__Transform__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getProcessAccess().getNameAssignment_1(), "rule__Process__NameAssignment_1");
					put(grammarAccess.getProcessAccess().getTryAssignment_3(), "rule__Process__TryAssignment_3");
					put(grammarAccess.getProcessAccess().getCatchAssignment_4(), "rule__Process__CatchAssignment_4");
					put(grammarAccess.getProcessAccess().getFinallyAssignment_5(), "rule__Process__FinallyAssignment_5");
					put(grammarAccess.getTryAccess().getNameAssignment_1(), "rule__Try__NameAssignment_1");
					put(grammarAccess.getTryAccess().getActionAssignment_3(), "rule__Try__ActionAssignment_3");
					put(grammarAccess.getFinallyAccess().getNameAssignment_1(), "rule__Finally__NameAssignment_1");
					put(grammarAccess.getFinallyAccess().getActionAssignment_3(), "rule__Finally__ActionAssignment_3");
					put(grammarAccess.getCatchAccess().getNameAssignment_1(), "rule__Catch__NameAssignment_1");
					put(grammarAccess.getCatchAccess().getActionAssignment_3(), "rule__Catch__ActionAssignment_3");
					put(grammarAccess.getFBCLeadAccess().getNameAssignment_2(), "rule__FBCLead__NameAssignment_2");
					put(grammarAccess.getFBCLeadAccess().getAccessTokenAssignment_4(), "rule__FBCLead__AccessTokenAssignment_4");
					put(grammarAccess.getFBCLeadAccess().getAppSecretAssignment_6(), "rule__FBCLead__AppSecretAssignment_6");
					put(grammarAccess.getFBCLeadAccess().getAccountIdAssignment_8(), "rule__FBCLead__AccountIdAssignment_8");
					put(grammarAccess.getFBCLeadAccess().getCampaignIdAssignment_10(), "rule__FBCLead__CampaignIdAssignment_10");
					put(grammarAccess.getFBCLeadAccess().getTargetAssignment_12(), "rule__FBCLead__TargetAssignment_12");
					put(grammarAccess.getFBCLeadAccess().getValueAssignment_15(), "rule__FBCLead__ValueAssignment_15");
					put(grammarAccess.getFBCLeadAccess().getConditionAssignment_18(), "rule__FBCLead__ConditionAssignment_18");
					put(grammarAccess.getDropfileAccess().getNameAssignment_2(), "rule__Dropfile__NameAssignment_2");
					put(grammarAccess.getDropfileAccess().getTargetAssignment_4(), "rule__Dropfile__TargetAssignment_4");
					put(grammarAccess.getDropfileAccess().getConditionAssignment_6(), "rule__Dropfile__ConditionAssignment_6");
					put(grammarAccess.getDoozleAccess().getNameAssignment_2(), "rule__Doozle__NameAssignment_2");
					put(grammarAccess.getDoozleAccess().getTargetAssignment_4(), "rule__Doozle__TargetAssignment_4");
					put(grammarAccess.getDoozleAccess().getOnAssignment_6(), "rule__Doozle__OnAssignment_6");
					put(grammarAccess.getDoozleAccess().getValueAssignment_9(), "rule__Doozle__ValueAssignment_9");
					put(grammarAccess.getDoozleAccess().getConditionAssignment_12(), "rule__Doozle__ConditionAssignment_12");
					put(grammarAccess.getRestAccess().getNameAssignment_2(), "rule__Rest__NameAssignment_2");
					put(grammarAccess.getRestAccess().getAuthtokenAssignment_4(), "rule__Rest__AuthtokenAssignment_4");
					put(grammarAccess.getRestAccess().getUrlAssignment_6(), "rule__Rest__UrlAssignment_6");
					put(grammarAccess.getRestAccess().getMethodAssignment_8(), "rule__Rest__MethodAssignment_8");
					put(grammarAccess.getRestAccess().getResourcedatafromAssignment_11(), "rule__Rest__ResourcedatafromAssignment_11");
					put(grammarAccess.getRestAccess().getUrldataAssignment_14(), "rule__Rest__UrldataAssignment_14");
					put(grammarAccess.getRestAccess().getHeaderdatafromAssignment_17(), "rule__Rest__HeaderdatafromAssignment_17");
					put(grammarAccess.getRestAccess().getHeaderdataAssignment_20(), "rule__Rest__HeaderdataAssignment_20");
					put(grammarAccess.getRestAccess().getPostdatafromAssignment_23(), "rule__Rest__PostdatafromAssignment_23");
					put(grammarAccess.getRestAccess().getParentNameAssignment_28(), "rule__Rest__ParentNameAssignment_28");
					put(grammarAccess.getRestAccess().getParentdataAssignment_29(), "rule__Rest__ParentdataAssignment_29");
					put(grammarAccess.getRestAccess().getPartsAssignment_30(), "rule__Rest__PartsAssignment_30");
					put(grammarAccess.getRestAccess().getAckdatatoAssignment_33(), "rule__Rest__AckdatatoAssignment_33");
					put(grammarAccess.getRestAccess().getAckdataAssignment_36(), "rule__Rest__AckdataAssignment_36");
					put(grammarAccess.getRestAccess().getConditionAssignment_40(), "rule__Rest__ConditionAssignment_40");
					put(grammarAccess.getRestPartAccess().getPartNameAssignment_2(), "rule__RestPart__PartNameAssignment_2");
					put(grammarAccess.getRestPartAccess().getPartDataAssignment_4(), "rule__RestPart__PartDataAssignment_4");
					put(grammarAccess.getTrelloGETAccess().getNameAssignment_2(), "rule__TrelloGET__NameAssignment_2");
					put(grammarAccess.getTrelloGETAccess().getAuthtokenAssignment_4(), "rule__TrelloGET__AuthtokenAssignment_4");
					put(grammarAccess.getTrelloGETAccess().getKeyAssignment_6(), "rule__TrelloGET__KeyAssignment_6");
					put(grammarAccess.getTrelloGETAccess().getUseraccountAssignment_8(), "rule__TrelloGET__UseraccountAssignment_8");
					put(grammarAccess.getTrelloGETAccess().getBoardAssignment_10(), "rule__TrelloGET__BoardAssignment_10");
					put(grammarAccess.getTrelloGETAccess().getTargetAssignment_12(), "rule__TrelloGET__TargetAssignment_12");
					put(grammarAccess.getTrelloGETAccess().getValueAssignment_15(), "rule__TrelloGET__ValueAssignment_15");
					put(grammarAccess.getTrelloGETAccess().getConditionAssignment_18(), "rule__TrelloGET__ConditionAssignment_18");
					put(grammarAccess.getTrelloPUTAccess().getNameAssignment_2(), "rule__TrelloPUT__NameAssignment_2");
					put(grammarAccess.getTrelloPUTAccess().getAuthtokenAssignment_4(), "rule__TrelloPUT__AuthtokenAssignment_4");
					put(grammarAccess.getTrelloPUTAccess().getKeyAssignment_6(), "rule__TrelloPUT__KeyAssignment_6");
					put(grammarAccess.getTrelloPUTAccess().getUseraccountAssignment_8(), "rule__TrelloPUT__UseraccountAssignment_8");
					put(grammarAccess.getTrelloPUTAccess().getListAssignment_10(), "rule__TrelloPUT__ListAssignment_10");
					put(grammarAccess.getTrelloPUTAccess().getSourceAssignment_12(), "rule__TrelloPUT__SourceAssignment_12");
					put(grammarAccess.getTrelloPUTAccess().getValueAssignment_15(), "rule__TrelloPUT__ValueAssignment_15");
					put(grammarAccess.getTrelloPUTAccess().getConditionAssignment_18(), "rule__TrelloPUT__ConditionAssignment_18");
					put(grammarAccess.getFetchAccess().getNameAssignment_2(), "rule__Fetch__NameAssignment_2");
					put(grammarAccess.getFetchAccess().getSourceAssignment_4(), "rule__Fetch__SourceAssignment_4");
					put(grammarAccess.getFetchAccess().getValueAssignment_7(), "rule__Fetch__ValueAssignment_7");
					put(grammarAccess.getFetchAccess().getConditionAssignment_10(), "rule__Fetch__ConditionAssignment_10");
					put(grammarAccess.getCallprocessAccess().getNameAssignment_2(), "rule__Callprocess__NameAssignment_2");
					put(grammarAccess.getCallprocessAccess().getTargetAssignment_4(), "rule__Callprocess__TargetAssignment_4");
					put(grammarAccess.getCallprocessAccess().getSourceAssignment_6(), "rule__Callprocess__SourceAssignment_6");
					put(grammarAccess.getCallprocessAccess().getDatasourceAssignment_8(), "rule__Callprocess__DatasourceAssignment_8");
					put(grammarAccess.getCallprocessAccess().getValueAssignment_11(), "rule__Callprocess__ValueAssignment_11");
					put(grammarAccess.getCallprocessAccess().getConditionAssignment_14(), "rule__Callprocess__ConditionAssignment_14");
					put(grammarAccess.getUpdatedauditAccess().getNameAssignment_2(), "rule__Updatedaudit__NameAssignment_2");
					put(grammarAccess.getUpdatedauditAccess().getLogsinkAssignment_4(), "rule__Updatedaudit__LogsinkAssignment_4");
					put(grammarAccess.getUpdatedauditAccess().getValueAssignment_7(), "rule__Updatedaudit__ValueAssignment_7");
					put(grammarAccess.getUpdatedauditAccess().getConditionAssignment_10(), "rule__Updatedaudit__ConditionAssignment_10");
					put(grammarAccess.getSmsAccess().getNameAssignment_2(), "rule__Sms__NameAssignment_2");
					put(grammarAccess.getSmsAccess().getTargetAssignment_4(), "rule__Sms__TargetAssignment_4");
					put(grammarAccess.getSmsAccess().getValueAssignment_7(), "rule__Sms__ValueAssignment_7");
					put(grammarAccess.getSmsAccess().getConditionAssignment_10(), "rule__Sms__ConditionAssignment_10");
					put(grammarAccess.getSlackPUTAccess().getNameAssignment_2(), "rule__SlackPUT__NameAssignment_2");
					put(grammarAccess.getSlackPUTAccess().getTeamAssignment_4(), "rule__SlackPUT__TeamAssignment_4");
					put(grammarAccess.getSlackPUTAccess().getChannelAssignment_6(), "rule__SlackPUT__ChannelAssignment_6");
					put(grammarAccess.getSlackPUTAccess().getValueAssignment_9(), "rule__SlackPUT__ValueAssignment_9");
					put(grammarAccess.getSlackPUTAccess().getConditionAssignment_12(), "rule__SlackPUT__ConditionAssignment_12");
					put(grammarAccess.getGooglecalPUTAccess().getNameAssignment_2(), "rule__GooglecalPUT__NameAssignment_2");
					put(grammarAccess.getGooglecalPUTAccess().getAuthstoreAssignment_4(), "rule__GooglecalPUT__AuthstoreAssignment_4");
					put(grammarAccess.getGooglecalPUTAccess().getKeyAssignment_6(), "rule__GooglecalPUT__KeyAssignment_6");
					put(grammarAccess.getGooglecalPUTAccess().getUseraccountAssignment_8(), "rule__GooglecalPUT__UseraccountAssignment_8");
					put(grammarAccess.getGooglecalPUTAccess().getSourceAssignment_10(), "rule__GooglecalPUT__SourceAssignment_10");
					put(grammarAccess.getGooglecalPUTAccess().getValueAssignment_13(), "rule__GooglecalPUT__ValueAssignment_13");
					put(grammarAccess.getGooglecalPUTAccess().getConditionAssignment_16(), "rule__GooglecalPUT__ConditionAssignment_16");
					put(grammarAccess.getCopydataAccess().getNameAssignment_2(), "rule__Copydata__NameAssignment_2");
					put(grammarAccess.getCopydataAccess().getSourceAssignment_4(), "rule__Copydata__SourceAssignment_4");
					put(grammarAccess.getCopydataAccess().getToAssignment_6(), "rule__Copydata__ToAssignment_6");
					put(grammarAccess.getCopydataAccess().getValueAssignment_9(), "rule__Copydata__ValueAssignment_9");
					put(grammarAccess.getCopydataAccess().getConditionAssignment_12(), "rule__Copydata__ConditionAssignment_12");
					put(grammarAccess.getWriteCsvAccess().getNameAssignment_2(), "rule__WriteCsv__NameAssignment_2");
					put(grammarAccess.getWriteCsvAccess().getSourceAssignment_4(), "rule__WriteCsv__SourceAssignment_4");
					put(grammarAccess.getWriteCsvAccess().getToAssignment_6(), "rule__WriteCsv__ToAssignment_6");
					put(grammarAccess.getWriteCsvAccess().getDelimAssignment_8(), "rule__WriteCsv__DelimAssignment_8");
					put(grammarAccess.getWriteCsvAccess().getValueAssignment_11(), "rule__WriteCsv__ValueAssignment_11");
					put(grammarAccess.getWriteCsvAccess().getConditionAssignment_14(), "rule__WriteCsv__ConditionAssignment_14");
					put(grammarAccess.getLoadCsvAccess().getNameAssignment_2(), "rule__LoadCsv__NameAssignment_2");
					put(grammarAccess.getLoadCsvAccess().getSourceAssignment_4(), "rule__LoadCsv__SourceAssignment_4");
					put(grammarAccess.getLoadCsvAccess().getToAssignment_6(), "rule__LoadCsv__ToAssignment_6");
					put(grammarAccess.getLoadCsvAccess().getDelimAssignment_8(), "rule__LoadCsv__DelimAssignment_8");
					put(grammarAccess.getLoadCsvAccess().getValueAssignment_11(), "rule__LoadCsv__ValueAssignment_11");
					put(grammarAccess.getLoadCsvAccess().getConditionAssignment_14(), "rule__LoadCsv__ConditionAssignment_14");
					put(grammarAccess.getTransformAccess().getNameAssignment_2(), "rule__Transform__NameAssignment_2");
					put(grammarAccess.getTransformAccess().getOnAssignment_4(), "rule__Transform__OnAssignment_4");
					put(grammarAccess.getTransformAccess().getValueAssignment_7(), "rule__Transform__ValueAssignment_7");
					put(grammarAccess.getTransformAccess().getConditionAssignment_10(), "rule__Transform__ConditionAssignment_10");
					put(grammarAccess.getExpressionAccess().getLhsAssignment_1(), "rule__Expression__LhsAssignment_1");
					put(grammarAccess.getExpressionAccess().getOperatorAssignment_2(), "rule__Expression__OperatorAssignment_2");
					put(grammarAccess.getExpressionAccess().getRhsAssignment_3(), "rule__Expression__RhsAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SparrowGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SparrowGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
