/*
 * generated by Xtext
 */
package org.etl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.etl.ui.internal.SparrowActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SparrowExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SparrowActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SparrowActivator.getInstance().getInjector(SparrowActivator.ORG_ETL_SPARROW);
	}
	
}
