/**
 * generated by Xtext 2.11.0
 */
package org.etl.sparrow;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Executescript</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.etl.sparrow.Executescript#getUsing <em>Using</em>}</li>
 *   <li>{@link org.etl.sparrow.Executescript#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.etl.sparrow.SparrowPackage#getExecutescript()
 * @model
 * @generated
 */
public interface Executescript extends Action
{
  /**
   * Returns the value of the '<em><b>Using</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Using</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Using</em>' attribute.
   * @see #setUsing(String)
   * @see org.etl.sparrow.SparrowPackage#getExecutescript_Using()
   * @model
   * @generated
   */
  String getUsing();

  /**
   * Sets the value of the '{@link org.etl.sparrow.Executescript#getUsing <em>Using</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Using</em>' attribute.
   * @see #getUsing()
   * @generated
   */
  void setUsing(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute list.
   * @see org.etl.sparrow.SparrowPackage#getExecutescript_Value()
   * @model unique="false"
   * @generated
   */
  EList<String> getValue();

} // Executescript
