/**
 * generated by Xtext 2.11.0
 */
package org.etl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Googlecal PUT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.etl.sparrow.GooglecalPUT#getAccount <em>Account</em>}</li>
 *   <li>{@link org.etl.sparrow.GooglecalPUT#getPrivateKey <em>Private Key</em>}</li>
 *   <li>{@link org.etl.sparrow.GooglecalPUT#getPtwelveFile <em>Ptwelve File</em>}</li>
 *   <li>{@link org.etl.sparrow.GooglecalPUT#getProject <em>Project</em>}</li>
 *   <li>{@link org.etl.sparrow.GooglecalPUT#getImpersonatedUser <em>Impersonated User</em>}</li>
 *   <li>{@link org.etl.sparrow.GooglecalPUT#getDbSrc <em>Db Src</em>}</li>
 *   <li>{@link org.etl.sparrow.GooglecalPUT#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.etl.sparrow.SparrowPackage#getGooglecalPUT()
 * @model
 * @generated
 */
public interface GooglecalPUT extends Action
{
  /**
   * Returns the value of the '<em><b>Account</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Account</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Account</em>' attribute.
   * @see #setAccount(String)
   * @see org.etl.sparrow.SparrowPackage#getGooglecalPUT_Account()
   * @model
   * @generated
   */
  String getAccount();

  /**
   * Sets the value of the '{@link org.etl.sparrow.GooglecalPUT#getAccount <em>Account</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Account</em>' attribute.
   * @see #getAccount()
   * @generated
   */
  void setAccount(String value);

  /**
   * Returns the value of the '<em><b>Private Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Private Key</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Private Key</em>' attribute.
   * @see #setPrivateKey(String)
   * @see org.etl.sparrow.SparrowPackage#getGooglecalPUT_PrivateKey()
   * @model
   * @generated
   */
  String getPrivateKey();

  /**
   * Sets the value of the '{@link org.etl.sparrow.GooglecalPUT#getPrivateKey <em>Private Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Private Key</em>' attribute.
   * @see #getPrivateKey()
   * @generated
   */
  void setPrivateKey(String value);

  /**
   * Returns the value of the '<em><b>Ptwelve File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ptwelve File</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ptwelve File</em>' attribute.
   * @see #setPtwelveFile(String)
   * @see org.etl.sparrow.SparrowPackage#getGooglecalPUT_PtwelveFile()
   * @model
   * @generated
   */
  String getPtwelveFile();

  /**
   * Sets the value of the '{@link org.etl.sparrow.GooglecalPUT#getPtwelveFile <em>Ptwelve File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ptwelve File</em>' attribute.
   * @see #getPtwelveFile()
   * @generated
   */
  void setPtwelveFile(String value);

  /**
   * Returns the value of the '<em><b>Project</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Project</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Project</em>' attribute.
   * @see #setProject(String)
   * @see org.etl.sparrow.SparrowPackage#getGooglecalPUT_Project()
   * @model
   * @generated
   */
  String getProject();

  /**
   * Sets the value of the '{@link org.etl.sparrow.GooglecalPUT#getProject <em>Project</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Project</em>' attribute.
   * @see #getProject()
   * @generated
   */
  void setProject(String value);

  /**
   * Returns the value of the '<em><b>Impersonated User</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Impersonated User</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Impersonated User</em>' attribute.
   * @see #setImpersonatedUser(String)
   * @see org.etl.sparrow.SparrowPackage#getGooglecalPUT_ImpersonatedUser()
   * @model
   * @generated
   */
  String getImpersonatedUser();

  /**
   * Sets the value of the '{@link org.etl.sparrow.GooglecalPUT#getImpersonatedUser <em>Impersonated User</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Impersonated User</em>' attribute.
   * @see #getImpersonatedUser()
   * @generated
   */
  void setImpersonatedUser(String value);

  /**
   * Returns the value of the '<em><b>Db Src</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Db Src</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db Src</em>' attribute.
   * @see #setDbSrc(String)
   * @see org.etl.sparrow.SparrowPackage#getGooglecalPUT_DbSrc()
   * @model
   * @generated
   */
  String getDbSrc();

  /**
   * Sets the value of the '{@link org.etl.sparrow.GooglecalPUT#getDbSrc <em>Db Src</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db Src</em>' attribute.
   * @see #getDbSrc()
   * @generated
   */
  void setDbSrc(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.etl.sparrow.SparrowPackage#getGooglecalPUT_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.etl.sparrow.GooglecalPUT#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // GooglecalPUT
