/**
 * generated by Xtext 2.11.0
 */
package org.etl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sms Lead Sms</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.etl.sparrow.SmsLeadSms#getUrl <em>Url</em>}</li>
 *   <li>{@link org.etl.sparrow.SmsLeadSms#getSender <em>Sender</em>}</li>
 *   <li>{@link org.etl.sparrow.SmsLeadSms#getAccount <em>Account</em>}</li>
 *   <li>{@link org.etl.sparrow.SmsLeadSms#getPrivateKey <em>Private Key</em>}</li>
 *   <li>{@link org.etl.sparrow.SmsLeadSms#getDbSrc <em>Db Src</em>}</li>
 *   <li>{@link org.etl.sparrow.SmsLeadSms#getValue <em>Value</em>}</li>
 *   <li>{@link org.etl.sparrow.SmsLeadSms#getDryrunNumber <em>Dryrun Number</em>}</li>
 * </ul>
 *
 * @see org.etl.sparrow.SparrowPackage#getSmsLeadSms()
 * @model
 * @generated
 */
public interface SmsLeadSms extends Action
{
  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Url</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute.
   * @see #setUrl(String)
   * @see org.etl.sparrow.SparrowPackage#getSmsLeadSms_Url()
   * @model
   * @generated
   */
  String getUrl();

  /**
   * Sets the value of the '{@link org.etl.sparrow.SmsLeadSms#getUrl <em>Url</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Url</em>' attribute.
   * @see #getUrl()
   * @generated
   */
  void setUrl(String value);

  /**
   * Returns the value of the '<em><b>Sender</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sender</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sender</em>' attribute.
   * @see #setSender(String)
   * @see org.etl.sparrow.SparrowPackage#getSmsLeadSms_Sender()
   * @model
   * @generated
   */
  String getSender();

  /**
   * Sets the value of the '{@link org.etl.sparrow.SmsLeadSms#getSender <em>Sender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sender</em>' attribute.
   * @see #getSender()
   * @generated
   */
  void setSender(String value);

  /**
   * Returns the value of the '<em><b>Account</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Account</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Account</em>' attribute.
   * @see #setAccount(String)
   * @see org.etl.sparrow.SparrowPackage#getSmsLeadSms_Account()
   * @model
   * @generated
   */
  String getAccount();

  /**
   * Sets the value of the '{@link org.etl.sparrow.SmsLeadSms#getAccount <em>Account</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Account</em>' attribute.
   * @see #getAccount()
   * @generated
   */
  void setAccount(String value);

  /**
   * Returns the value of the '<em><b>Private Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Private Key</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Private Key</em>' attribute.
   * @see #setPrivateKey(String)
   * @see org.etl.sparrow.SparrowPackage#getSmsLeadSms_PrivateKey()
   * @model
   * @generated
   */
  String getPrivateKey();

  /**
   * Sets the value of the '{@link org.etl.sparrow.SmsLeadSms#getPrivateKey <em>Private Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Private Key</em>' attribute.
   * @see #getPrivateKey()
   * @generated
   */
  void setPrivateKey(String value);

  /**
   * Returns the value of the '<em><b>Db Src</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Db Src</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Db Src</em>' attribute.
   * @see #setDbSrc(String)
   * @see org.etl.sparrow.SparrowPackage#getSmsLeadSms_DbSrc()
   * @model
   * @generated
   */
  String getDbSrc();

  /**
   * Sets the value of the '{@link org.etl.sparrow.SmsLeadSms#getDbSrc <em>Db Src</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Db Src</em>' attribute.
   * @see #getDbSrc()
   * @generated
   */
  void setDbSrc(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.etl.sparrow.SparrowPackage#getSmsLeadSms_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.etl.sparrow.SmsLeadSms#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Dryrun Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dryrun Number</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dryrun Number</em>' attribute.
   * @see #setDryrunNumber(String)
   * @see org.etl.sparrow.SparrowPackage#getSmsLeadSms_DryrunNumber()
   * @model
   * @generated
   */
  String getDryrunNumber();

  /**
   * Sets the value of the '{@link org.etl.sparrow.SmsLeadSms#getDryrunNumber <em>Dryrun Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dryrun Number</em>' attribute.
   * @see #getDryrunNumber()
   * @generated
   */
  void setDryrunNumber(String value);

} // SmsLeadSms
