/**
 * generated by Xtext 2.12.0
 */
package org.etl.sparrow;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.etl.sparrow.SparrowFactory
 * @model kind="package"
 * @generated
 */
public interface SparrowPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sparrow";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.junome.in/sparrow";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sparrow";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SparrowPackage eINSTANCE = org.etl.sparrow.impl.SparrowPackageImpl.init();

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.ProcessImpl <em>Process</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.ProcessImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getProcess()
   * @generated
   */
  int PROCESS = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__NAME = 0;

  /**
   * The feature id for the '<em><b>Try</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__TRY = 1;

  /**
   * The feature id for the '<em><b>Catch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__CATCH = 2;

  /**
   * The feature id for the '<em><b>Finally</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS__FINALLY = 3;

  /**
   * The number of structural features of the '<em>Process</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCESS_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.TryImpl <em>Try</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.TryImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getTry()
   * @generated
   */
  int TRY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRY__NAME = 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRY__ACTION = 1;

  /**
   * The number of structural features of the '<em>Try</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.FinallyImpl <em>Finally</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.FinallyImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getFinally()
   * @generated
   */
  int FINALLY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINALLY__NAME = 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINALLY__ACTION = 1;

  /**
   * The number of structural features of the '<em>Finally</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FINALLY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.CatchImpl <em>Catch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.CatchImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getCatch()
   * @generated
   */
  int CATCH = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATCH__NAME = 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATCH__ACTION = 1;

  /**
   * The number of structural features of the '<em>Catch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CATCH_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.ActionImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getAction()
   * @generated
   */
  int ACTION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.DropfileImpl <em>Dropfile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.DropfileImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getDropfile()
   * @generated
   */
  int DROPFILE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROPFILE__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROPFILE__TARGET = ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Dropfile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROPFILE_FEATURE_COUNT = ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.DoozleImpl <em>Doozle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.DoozleImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getDoozle()
   * @generated
   */
  int DOOZLE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOZLE__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOZLE__TARGET = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>On</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOZLE__ON = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOZLE__VALUE = ACTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Doozle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOOZLE_FEATURE_COUNT = ACTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.RestImpl <em>Rest</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.RestImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getRest()
   * @generated
   */
  int REST = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Authtoken</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__AUTHTOKEN = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__URL = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__METHOD = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Headerdatafrom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__HEADERDATAFROM = ACTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Headerdata</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__HEADERDATA = ACTION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Postdatafrom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__POSTDATAFROM = ACTION_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Parent Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__PARENT_NAME = ACTION_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Parentdata</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__PARENTDATA = ACTION_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Parts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__PARTS = ACTION_FEATURE_COUNT + 8;

  /**
   * The feature id for the '<em><b>Ackdatato</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__ACKDATATO = ACTION_FEATURE_COUNT + 9;

  /**
   * The feature id for the '<em><b>Ackdata</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__ACKDATA = ACTION_FEATURE_COUNT + 10;

  /**
   * The number of structural features of the '<em>Rest</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_FEATURE_COUNT = ACTION_FEATURE_COUNT + 11;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.RestPartImpl <em>Rest Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.RestPartImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getRestPart()
   * @generated
   */
  int REST_PART = 8;

  /**
   * The feature id for the '<em><b>Part Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_PART__PART_NAME = 0;

  /**
   * The feature id for the '<em><b>Part Data</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_PART__PART_DATA = 1;

  /**
   * The number of structural features of the '<em>Rest Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_PART_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.TrelloGETImpl <em>Trello GET</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.TrelloGETImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getTrelloGET()
   * @generated
   */
  int TRELLO_GET = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_GET__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Authtoken</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_GET__AUTHTOKEN = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_GET__KEY = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Useraccount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_GET__USERACCOUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Board</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_GET__BOARD = ACTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_GET__TARGET = ACTION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_GET__VALUE = ACTION_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_GET__CONDITION = ACTION_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Trello GET</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_GET_FEATURE_COUNT = ACTION_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.TrelloPUTImpl <em>Trello PUT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.TrelloPUTImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getTrelloPUT()
   * @generated
   */
  int TRELLO_PUT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_PUT__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Authtoken</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_PUT__AUTHTOKEN = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_PUT__KEY = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Useraccount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_PUT__USERACCOUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_PUT__LIST = ACTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_PUT__SOURCE = ACTION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_PUT__VALUE = ACTION_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_PUT__CONDITION = ACTION_FEATURE_COUNT + 6;

  /**
   * The number of structural features of the '<em>Trello PUT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRELLO_PUT_FEATURE_COUNT = ACTION_FEATURE_COUNT + 7;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.FetchImpl <em>Fetch</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.FetchImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getFetch()
   * @generated
   */
  int FETCH = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH__SOURCE = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH__VALUE = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH__CONDITION = ACTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Fetch</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_FEATURE_COUNT = ACTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.CallprocessImpl <em>Callprocess</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.CallprocessImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getCallprocess()
   * @generated
   */
  int CALLPROCESS = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLPROCESS__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLPROCESS__TARGET = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLPROCESS__SOURCE = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Datasource</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLPROCESS__DATASOURCE = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLPROCESS__VALUE = ACTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLPROCESS__CONDITION = ACTION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Callprocess</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALLPROCESS_FEATURE_COUNT = ACTION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.UpdatedauditImpl <em>Updatedaudit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.UpdatedauditImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getUpdatedaudit()
   * @generated
   */
  int UPDATEDAUDIT = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATEDAUDIT__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Logsink</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATEDAUDIT__LOGSINK = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATEDAUDIT__VALUE = ACTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Updatedaudit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPDATEDAUDIT_FEATURE_COUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.SmsImpl <em>Sms</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.SmsImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getSms()
   * @generated
   */
  int SMS = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMS__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMS__TARGET = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMS__VALUE = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMS__CONDITION = ACTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Sms</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMS_FEATURE_COUNT = ACTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.SlackPUTImpl <em>Slack PUT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.SlackPUTImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getSlackPUT()
   * @generated
   */
  int SLACK_PUT = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLACK_PUT__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Team</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLACK_PUT__TEAM = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Channel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLACK_PUT__CHANNEL = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLACK_PUT__VALUE = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLACK_PUT__CONDITION = ACTION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Slack PUT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SLACK_PUT_FEATURE_COUNT = ACTION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.GooglecalPUTImpl <em>Googlecal PUT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.GooglecalPUTImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getGooglecalPUT()
   * @generated
   */
  int GOOGLECAL_PUT = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOOGLECAL_PUT__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Authstore</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOOGLECAL_PUT__AUTHSTORE = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOOGLECAL_PUT__KEY = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Useraccount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOOGLECAL_PUT__USERACCOUNT = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOOGLECAL_PUT__SOURCE = ACTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOOGLECAL_PUT__VALUE = ACTION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOOGLECAL_PUT__CONDITION = ACTION_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Googlecal PUT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOOGLECAL_PUT_FEATURE_COUNT = ACTION_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.CopydataImpl <em>Copydata</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.CopydataImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getCopydata()
   * @generated
   */
  int COPYDATA = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPYDATA__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPYDATA__SOURCE = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPYDATA__TO = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPYDATA__VALUE = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPYDATA__CONDITION = ACTION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Copydata</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COPYDATA_FEATURE_COUNT = ACTION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.WriteCsvImpl <em>Write Csv</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.WriteCsvImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getWriteCsv()
   * @generated
   */
  int WRITE_CSV = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__SOURCE = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__TO = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Delim</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__DELIM = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__VALUE = ACTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV__CONDITION = ACTION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Write Csv</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_CSV_FEATURE_COUNT = ACTION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.LoadCsvImpl <em>Load Csv</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.LoadCsvImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getLoadCsv()
   * @generated
   */
  int LOAD_CSV = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_CSV__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_CSV__SOURCE = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_CSV__TO = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Delim</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_CSV__DELIM = ACTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_CSV__VALUE = ACTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_CSV__CONDITION = ACTION_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Load Csv</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_CSV_FEATURE_COUNT = ACTION_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.etl.sparrow.impl.TransformImpl <em>Transform</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.etl.sparrow.impl.TransformImpl
   * @see org.etl.sparrow.impl.SparrowPackageImpl#getTransform()
   * @generated
   */
  int TRANSFORM = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORM__NAME = ACTION__NAME;

  /**
   * The feature id for the '<em><b>On</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORM__ON = ACTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORM__VALUE = ACTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORM__CONDITION = ACTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Transform</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORM_FEATURE_COUNT = ACTION_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Process <em>Process</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Process</em>'.
   * @see org.etl.sparrow.Process
   * @generated
   */
  EClass getProcess();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Process#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.etl.sparrow.Process#getName()
   * @see #getProcess()
   * @generated
   */
  EAttribute getProcess_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.etl.sparrow.Process#getTry <em>Try</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Try</em>'.
   * @see org.etl.sparrow.Process#getTry()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Try();

  /**
   * Returns the meta object for the containment reference '{@link org.etl.sparrow.Process#getCatch <em>Catch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Catch</em>'.
   * @see org.etl.sparrow.Process#getCatch()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Catch();

  /**
   * Returns the meta object for the containment reference '{@link org.etl.sparrow.Process#getFinally <em>Finally</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Finally</em>'.
   * @see org.etl.sparrow.Process#getFinally()
   * @see #getProcess()
   * @generated
   */
  EReference getProcess_Finally();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Try <em>Try</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Try</em>'.
   * @see org.etl.sparrow.Try
   * @generated
   */
  EClass getTry();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Try#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.etl.sparrow.Try#getName()
   * @see #getTry()
   * @generated
   */
  EAttribute getTry_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.etl.sparrow.Try#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action</em>'.
   * @see org.etl.sparrow.Try#getAction()
   * @see #getTry()
   * @generated
   */
  EReference getTry_Action();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Finally <em>Finally</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Finally</em>'.
   * @see org.etl.sparrow.Finally
   * @generated
   */
  EClass getFinally();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Finally#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.etl.sparrow.Finally#getName()
   * @see #getFinally()
   * @generated
   */
  EAttribute getFinally_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.etl.sparrow.Finally#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action</em>'.
   * @see org.etl.sparrow.Finally#getAction()
   * @see #getFinally()
   * @generated
   */
  EReference getFinally_Action();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Catch <em>Catch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Catch</em>'.
   * @see org.etl.sparrow.Catch
   * @generated
   */
  EClass getCatch();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Catch#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.etl.sparrow.Catch#getName()
   * @see #getCatch()
   * @generated
   */
  EAttribute getCatch_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.etl.sparrow.Catch#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action</em>'.
   * @see org.etl.sparrow.Catch#getAction()
   * @see #getCatch()
   * @generated
   */
  EReference getCatch_Action();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.etl.sparrow.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Action#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.etl.sparrow.Action#getName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Name();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Dropfile <em>Dropfile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dropfile</em>'.
   * @see org.etl.sparrow.Dropfile
   * @generated
   */
  EClass getDropfile();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Dropfile#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.etl.sparrow.Dropfile#getTarget()
   * @see #getDropfile()
   * @generated
   */
  EAttribute getDropfile_Target();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Doozle <em>Doozle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Doozle</em>'.
   * @see org.etl.sparrow.Doozle
   * @generated
   */
  EClass getDoozle();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Doozle#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.etl.sparrow.Doozle#getTarget()
   * @see #getDoozle()
   * @generated
   */
  EAttribute getDoozle_Target();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Doozle#getOn <em>On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>On</em>'.
   * @see org.etl.sparrow.Doozle#getOn()
   * @see #getDoozle()
   * @generated
   */
  EAttribute getDoozle_On();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Doozle#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.Doozle#getValue()
   * @see #getDoozle()
   * @generated
   */
  EAttribute getDoozle_Value();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Rest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rest</em>'.
   * @see org.etl.sparrow.Rest
   * @generated
   */
  EClass getRest();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Rest#getAuthtoken <em>Authtoken</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Authtoken</em>'.
   * @see org.etl.sparrow.Rest#getAuthtoken()
   * @see #getRest()
   * @generated
   */
  EAttribute getRest_Authtoken();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Rest#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.etl.sparrow.Rest#getUrl()
   * @see #getRest()
   * @generated
   */
  EAttribute getRest_Url();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Rest#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method</em>'.
   * @see org.etl.sparrow.Rest#getMethod()
   * @see #getRest()
   * @generated
   */
  EAttribute getRest_Method();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Rest#getHeaderdatafrom <em>Headerdatafrom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Headerdatafrom</em>'.
   * @see org.etl.sparrow.Rest#getHeaderdatafrom()
   * @see #getRest()
   * @generated
   */
  EAttribute getRest_Headerdatafrom();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Rest#getHeaderdata <em>Headerdata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Headerdata</em>'.
   * @see org.etl.sparrow.Rest#getHeaderdata()
   * @see #getRest()
   * @generated
   */
  EAttribute getRest_Headerdata();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Rest#getPostdatafrom <em>Postdatafrom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Postdatafrom</em>'.
   * @see org.etl.sparrow.Rest#getPostdatafrom()
   * @see #getRest()
   * @generated
   */
  EAttribute getRest_Postdatafrom();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Rest#getParentName <em>Parent Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parent Name</em>'.
   * @see org.etl.sparrow.Rest#getParentName()
   * @see #getRest()
   * @generated
   */
  EAttribute getRest_ParentName();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Rest#getParentdata <em>Parentdata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parentdata</em>'.
   * @see org.etl.sparrow.Rest#getParentdata()
   * @see #getRest()
   * @generated
   */
  EAttribute getRest_Parentdata();

  /**
   * Returns the meta object for the containment reference list '{@link org.etl.sparrow.Rest#getParts <em>Parts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parts</em>'.
   * @see org.etl.sparrow.Rest#getParts()
   * @see #getRest()
   * @generated
   */
  EReference getRest_Parts();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Rest#getAckdatato <em>Ackdatato</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ackdatato</em>'.
   * @see org.etl.sparrow.Rest#getAckdatato()
   * @see #getRest()
   * @generated
   */
  EAttribute getRest_Ackdatato();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Rest#getAckdata <em>Ackdata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ackdata</em>'.
   * @see org.etl.sparrow.Rest#getAckdata()
   * @see #getRest()
   * @generated
   */
  EAttribute getRest_Ackdata();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.RestPart <em>Rest Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rest Part</em>'.
   * @see org.etl.sparrow.RestPart
   * @generated
   */
  EClass getRestPart();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.RestPart#getPartName <em>Part Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Part Name</em>'.
   * @see org.etl.sparrow.RestPart#getPartName()
   * @see #getRestPart()
   * @generated
   */
  EAttribute getRestPart_PartName();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.RestPart#getPartData <em>Part Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Part Data</em>'.
   * @see org.etl.sparrow.RestPart#getPartData()
   * @see #getRestPart()
   * @generated
   */
  EAttribute getRestPart_PartData();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.TrelloGET <em>Trello GET</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trello GET</em>'.
   * @see org.etl.sparrow.TrelloGET
   * @generated
   */
  EClass getTrelloGET();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloGET#getAuthtoken <em>Authtoken</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Authtoken</em>'.
   * @see org.etl.sparrow.TrelloGET#getAuthtoken()
   * @see #getTrelloGET()
   * @generated
   */
  EAttribute getTrelloGET_Authtoken();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloGET#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.etl.sparrow.TrelloGET#getKey()
   * @see #getTrelloGET()
   * @generated
   */
  EAttribute getTrelloGET_Key();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloGET#getUseraccount <em>Useraccount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Useraccount</em>'.
   * @see org.etl.sparrow.TrelloGET#getUseraccount()
   * @see #getTrelloGET()
   * @generated
   */
  EAttribute getTrelloGET_Useraccount();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloGET#getBoard <em>Board</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Board</em>'.
   * @see org.etl.sparrow.TrelloGET#getBoard()
   * @see #getTrelloGET()
   * @generated
   */
  EAttribute getTrelloGET_Board();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloGET#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.etl.sparrow.TrelloGET#getTarget()
   * @see #getTrelloGET()
   * @generated
   */
  EAttribute getTrelloGET_Target();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloGET#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.TrelloGET#getValue()
   * @see #getTrelloGET()
   * @generated
   */
  EAttribute getTrelloGET_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloGET#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.TrelloGET#getCondition()
   * @see #getTrelloGET()
   * @generated
   */
  EAttribute getTrelloGET_Condition();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.TrelloPUT <em>Trello PUT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trello PUT</em>'.
   * @see org.etl.sparrow.TrelloPUT
   * @generated
   */
  EClass getTrelloPUT();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloPUT#getAuthtoken <em>Authtoken</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Authtoken</em>'.
   * @see org.etl.sparrow.TrelloPUT#getAuthtoken()
   * @see #getTrelloPUT()
   * @generated
   */
  EAttribute getTrelloPUT_Authtoken();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloPUT#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.etl.sparrow.TrelloPUT#getKey()
   * @see #getTrelloPUT()
   * @generated
   */
  EAttribute getTrelloPUT_Key();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloPUT#getUseraccount <em>Useraccount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Useraccount</em>'.
   * @see org.etl.sparrow.TrelloPUT#getUseraccount()
   * @see #getTrelloPUT()
   * @generated
   */
  EAttribute getTrelloPUT_Useraccount();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloPUT#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>List</em>'.
   * @see org.etl.sparrow.TrelloPUT#getList()
   * @see #getTrelloPUT()
   * @generated
   */
  EAttribute getTrelloPUT_List();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloPUT#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see org.etl.sparrow.TrelloPUT#getSource()
   * @see #getTrelloPUT()
   * @generated
   */
  EAttribute getTrelloPUT_Source();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloPUT#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.TrelloPUT#getValue()
   * @see #getTrelloPUT()
   * @generated
   */
  EAttribute getTrelloPUT_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.TrelloPUT#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.TrelloPUT#getCondition()
   * @see #getTrelloPUT()
   * @generated
   */
  EAttribute getTrelloPUT_Condition();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Fetch <em>Fetch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fetch</em>'.
   * @see org.etl.sparrow.Fetch
   * @generated
   */
  EClass getFetch();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Fetch#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see org.etl.sparrow.Fetch#getSource()
   * @see #getFetch()
   * @generated
   */
  EAttribute getFetch_Source();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Fetch#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.Fetch#getValue()
   * @see #getFetch()
   * @generated
   */
  EAttribute getFetch_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Fetch#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.Fetch#getCondition()
   * @see #getFetch()
   * @generated
   */
  EAttribute getFetch_Condition();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Callprocess <em>Callprocess</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Callprocess</em>'.
   * @see org.etl.sparrow.Callprocess
   * @generated
   */
  EClass getCallprocess();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Callprocess#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.etl.sparrow.Callprocess#getTarget()
   * @see #getCallprocess()
   * @generated
   */
  EAttribute getCallprocess_Target();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Callprocess#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see org.etl.sparrow.Callprocess#getSource()
   * @see #getCallprocess()
   * @generated
   */
  EAttribute getCallprocess_Source();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Callprocess#getDatasource <em>Datasource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Datasource</em>'.
   * @see org.etl.sparrow.Callprocess#getDatasource()
   * @see #getCallprocess()
   * @generated
   */
  EAttribute getCallprocess_Datasource();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Callprocess#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.Callprocess#getValue()
   * @see #getCallprocess()
   * @generated
   */
  EAttribute getCallprocess_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Callprocess#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.Callprocess#getCondition()
   * @see #getCallprocess()
   * @generated
   */
  EAttribute getCallprocess_Condition();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Updatedaudit <em>Updatedaudit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Updatedaudit</em>'.
   * @see org.etl.sparrow.Updatedaudit
   * @generated
   */
  EClass getUpdatedaudit();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Updatedaudit#getLogsink <em>Logsink</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Logsink</em>'.
   * @see org.etl.sparrow.Updatedaudit#getLogsink()
   * @see #getUpdatedaudit()
   * @generated
   */
  EAttribute getUpdatedaudit_Logsink();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Updatedaudit#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.Updatedaudit#getValue()
   * @see #getUpdatedaudit()
   * @generated
   */
  EAttribute getUpdatedaudit_Value();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Sms <em>Sms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sms</em>'.
   * @see org.etl.sparrow.Sms
   * @generated
   */
  EClass getSms();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Sms#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.etl.sparrow.Sms#getTarget()
   * @see #getSms()
   * @generated
   */
  EAttribute getSms_Target();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Sms#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.Sms#getValue()
   * @see #getSms()
   * @generated
   */
  EAttribute getSms_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Sms#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.Sms#getCondition()
   * @see #getSms()
   * @generated
   */
  EAttribute getSms_Condition();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.SlackPUT <em>Slack PUT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Slack PUT</em>'.
   * @see org.etl.sparrow.SlackPUT
   * @generated
   */
  EClass getSlackPUT();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.SlackPUT#getTeam <em>Team</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Team</em>'.
   * @see org.etl.sparrow.SlackPUT#getTeam()
   * @see #getSlackPUT()
   * @generated
   */
  EAttribute getSlackPUT_Team();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.SlackPUT#getChannel <em>Channel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Channel</em>'.
   * @see org.etl.sparrow.SlackPUT#getChannel()
   * @see #getSlackPUT()
   * @generated
   */
  EAttribute getSlackPUT_Channel();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.SlackPUT#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.SlackPUT#getValue()
   * @see #getSlackPUT()
   * @generated
   */
  EAttribute getSlackPUT_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.SlackPUT#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.SlackPUT#getCondition()
   * @see #getSlackPUT()
   * @generated
   */
  EAttribute getSlackPUT_Condition();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.GooglecalPUT <em>Googlecal PUT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Googlecal PUT</em>'.
   * @see org.etl.sparrow.GooglecalPUT
   * @generated
   */
  EClass getGooglecalPUT();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.GooglecalPUT#getAuthstore <em>Authstore</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Authstore</em>'.
   * @see org.etl.sparrow.GooglecalPUT#getAuthstore()
   * @see #getGooglecalPUT()
   * @generated
   */
  EAttribute getGooglecalPUT_Authstore();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.GooglecalPUT#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Key</em>'.
   * @see org.etl.sparrow.GooglecalPUT#getKey()
   * @see #getGooglecalPUT()
   * @generated
   */
  EAttribute getGooglecalPUT_Key();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.GooglecalPUT#getUseraccount <em>Useraccount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Useraccount</em>'.
   * @see org.etl.sparrow.GooglecalPUT#getUseraccount()
   * @see #getGooglecalPUT()
   * @generated
   */
  EAttribute getGooglecalPUT_Useraccount();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.GooglecalPUT#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see org.etl.sparrow.GooglecalPUT#getSource()
   * @see #getGooglecalPUT()
   * @generated
   */
  EAttribute getGooglecalPUT_Source();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.GooglecalPUT#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.GooglecalPUT#getValue()
   * @see #getGooglecalPUT()
   * @generated
   */
  EAttribute getGooglecalPUT_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.GooglecalPUT#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.GooglecalPUT#getCondition()
   * @see #getGooglecalPUT()
   * @generated
   */
  EAttribute getGooglecalPUT_Condition();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Copydata <em>Copydata</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Copydata</em>'.
   * @see org.etl.sparrow.Copydata
   * @generated
   */
  EClass getCopydata();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Copydata#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see org.etl.sparrow.Copydata#getSource()
   * @see #getCopydata()
   * @generated
   */
  EAttribute getCopydata_Source();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Copydata#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To</em>'.
   * @see org.etl.sparrow.Copydata#getTo()
   * @see #getCopydata()
   * @generated
   */
  EAttribute getCopydata_To();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Copydata#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.Copydata#getValue()
   * @see #getCopydata()
   * @generated
   */
  EAttribute getCopydata_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Copydata#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.Copydata#getCondition()
   * @see #getCopydata()
   * @generated
   */
  EAttribute getCopydata_Condition();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.WriteCsv <em>Write Csv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Write Csv</em>'.
   * @see org.etl.sparrow.WriteCsv
   * @generated
   */
  EClass getWriteCsv();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.WriteCsv#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see org.etl.sparrow.WriteCsv#getSource()
   * @see #getWriteCsv()
   * @generated
   */
  EAttribute getWriteCsv_Source();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.WriteCsv#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To</em>'.
   * @see org.etl.sparrow.WriteCsv#getTo()
   * @see #getWriteCsv()
   * @generated
   */
  EAttribute getWriteCsv_To();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.WriteCsv#getDelim <em>Delim</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Delim</em>'.
   * @see org.etl.sparrow.WriteCsv#getDelim()
   * @see #getWriteCsv()
   * @generated
   */
  EAttribute getWriteCsv_Delim();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.WriteCsv#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.WriteCsv#getValue()
   * @see #getWriteCsv()
   * @generated
   */
  EAttribute getWriteCsv_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.WriteCsv#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.WriteCsv#getCondition()
   * @see #getWriteCsv()
   * @generated
   */
  EAttribute getWriteCsv_Condition();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.LoadCsv <em>Load Csv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Load Csv</em>'.
   * @see org.etl.sparrow.LoadCsv
   * @generated
   */
  EClass getLoadCsv();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.LoadCsv#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see org.etl.sparrow.LoadCsv#getSource()
   * @see #getLoadCsv()
   * @generated
   */
  EAttribute getLoadCsv_Source();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.LoadCsv#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To</em>'.
   * @see org.etl.sparrow.LoadCsv#getTo()
   * @see #getLoadCsv()
   * @generated
   */
  EAttribute getLoadCsv_To();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.LoadCsv#getDelim <em>Delim</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Delim</em>'.
   * @see org.etl.sparrow.LoadCsv#getDelim()
   * @see #getLoadCsv()
   * @generated
   */
  EAttribute getLoadCsv_Delim();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.LoadCsv#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.etl.sparrow.LoadCsv#getValue()
   * @see #getLoadCsv()
   * @generated
   */
  EAttribute getLoadCsv_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.LoadCsv#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.LoadCsv#getCondition()
   * @see #getLoadCsv()
   * @generated
   */
  EAttribute getLoadCsv_Condition();

  /**
   * Returns the meta object for class '{@link org.etl.sparrow.Transform <em>Transform</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transform</em>'.
   * @see org.etl.sparrow.Transform
   * @generated
   */
  EClass getTransform();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Transform#getOn <em>On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>On</em>'.
   * @see org.etl.sparrow.Transform#getOn()
   * @see #getTransform()
   * @generated
   */
  EAttribute getTransform_On();

  /**
   * Returns the meta object for the attribute list '{@link org.etl.sparrow.Transform#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.etl.sparrow.Transform#getValue()
   * @see #getTransform()
   * @generated
   */
  EAttribute getTransform_Value();

  /**
   * Returns the meta object for the attribute '{@link org.etl.sparrow.Transform#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.etl.sparrow.Transform#getCondition()
   * @see #getTransform()
   * @generated
   */
  EAttribute getTransform_Condition();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SparrowFactory getSparrowFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.ProcessImpl <em>Process</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.ProcessImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getProcess()
     * @generated
     */
    EClass PROCESS = eINSTANCE.getProcess();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCESS__NAME = eINSTANCE.getProcess_Name();

    /**
     * The meta object literal for the '<em><b>Try</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__TRY = eINSTANCE.getProcess_Try();

    /**
     * The meta object literal for the '<em><b>Catch</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__CATCH = eINSTANCE.getProcess_Catch();

    /**
     * The meta object literal for the '<em><b>Finally</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCESS__FINALLY = eINSTANCE.getProcess_Finally();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.TryImpl <em>Try</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.TryImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getTry()
     * @generated
     */
    EClass TRY = eINSTANCE.getTry();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRY__NAME = eINSTANCE.getTry_Name();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRY__ACTION = eINSTANCE.getTry_Action();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.FinallyImpl <em>Finally</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.FinallyImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getFinally()
     * @generated
     */
    EClass FINALLY = eINSTANCE.getFinally();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FINALLY__NAME = eINSTANCE.getFinally_Name();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FINALLY__ACTION = eINSTANCE.getFinally_Action();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.CatchImpl <em>Catch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.CatchImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getCatch()
     * @generated
     */
    EClass CATCH = eINSTANCE.getCatch();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CATCH__NAME = eINSTANCE.getCatch_Name();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CATCH__ACTION = eINSTANCE.getCatch_Action();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.ActionImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getAction_Name();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.DropfileImpl <em>Dropfile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.DropfileImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getDropfile()
     * @generated
     */
    EClass DROPFILE = eINSTANCE.getDropfile();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DROPFILE__TARGET = eINSTANCE.getDropfile_Target();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.DoozleImpl <em>Doozle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.DoozleImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getDoozle()
     * @generated
     */
    EClass DOOZLE = eINSTANCE.getDoozle();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOOZLE__TARGET = eINSTANCE.getDoozle_Target();

    /**
     * The meta object literal for the '<em><b>On</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOOZLE__ON = eINSTANCE.getDoozle_On();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOOZLE__VALUE = eINSTANCE.getDoozle_Value();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.RestImpl <em>Rest</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.RestImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getRest()
     * @generated
     */
    EClass REST = eINSTANCE.getRest();

    /**
     * The meta object literal for the '<em><b>Authtoken</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST__AUTHTOKEN = eINSTANCE.getRest_Authtoken();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST__URL = eINSTANCE.getRest_Url();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST__METHOD = eINSTANCE.getRest_Method();

    /**
     * The meta object literal for the '<em><b>Headerdatafrom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST__HEADERDATAFROM = eINSTANCE.getRest_Headerdatafrom();

    /**
     * The meta object literal for the '<em><b>Headerdata</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST__HEADERDATA = eINSTANCE.getRest_Headerdata();

    /**
     * The meta object literal for the '<em><b>Postdatafrom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST__POSTDATAFROM = eINSTANCE.getRest_Postdatafrom();

    /**
     * The meta object literal for the '<em><b>Parent Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST__PARENT_NAME = eINSTANCE.getRest_ParentName();

    /**
     * The meta object literal for the '<em><b>Parentdata</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST__PARENTDATA = eINSTANCE.getRest_Parentdata();

    /**
     * The meta object literal for the '<em><b>Parts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REST__PARTS = eINSTANCE.getRest_Parts();

    /**
     * The meta object literal for the '<em><b>Ackdatato</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST__ACKDATATO = eINSTANCE.getRest_Ackdatato();

    /**
     * The meta object literal for the '<em><b>Ackdata</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST__ACKDATA = eINSTANCE.getRest_Ackdata();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.RestPartImpl <em>Rest Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.RestPartImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getRestPart()
     * @generated
     */
    EClass REST_PART = eINSTANCE.getRestPart();

    /**
     * The meta object literal for the '<em><b>Part Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST_PART__PART_NAME = eINSTANCE.getRestPart_PartName();

    /**
     * The meta object literal for the '<em><b>Part Data</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REST_PART__PART_DATA = eINSTANCE.getRestPart_PartData();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.TrelloGETImpl <em>Trello GET</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.TrelloGETImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getTrelloGET()
     * @generated
     */
    EClass TRELLO_GET = eINSTANCE.getTrelloGET();

    /**
     * The meta object literal for the '<em><b>Authtoken</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_GET__AUTHTOKEN = eINSTANCE.getTrelloGET_Authtoken();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_GET__KEY = eINSTANCE.getTrelloGET_Key();

    /**
     * The meta object literal for the '<em><b>Useraccount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_GET__USERACCOUNT = eINSTANCE.getTrelloGET_Useraccount();

    /**
     * The meta object literal for the '<em><b>Board</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_GET__BOARD = eINSTANCE.getTrelloGET_Board();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_GET__TARGET = eINSTANCE.getTrelloGET_Target();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_GET__VALUE = eINSTANCE.getTrelloGET_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_GET__CONDITION = eINSTANCE.getTrelloGET_Condition();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.TrelloPUTImpl <em>Trello PUT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.TrelloPUTImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getTrelloPUT()
     * @generated
     */
    EClass TRELLO_PUT = eINSTANCE.getTrelloPUT();

    /**
     * The meta object literal for the '<em><b>Authtoken</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_PUT__AUTHTOKEN = eINSTANCE.getTrelloPUT_Authtoken();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_PUT__KEY = eINSTANCE.getTrelloPUT_Key();

    /**
     * The meta object literal for the '<em><b>Useraccount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_PUT__USERACCOUNT = eINSTANCE.getTrelloPUT_Useraccount();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_PUT__LIST = eINSTANCE.getTrelloPUT_List();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_PUT__SOURCE = eINSTANCE.getTrelloPUT_Source();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_PUT__VALUE = eINSTANCE.getTrelloPUT_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRELLO_PUT__CONDITION = eINSTANCE.getTrelloPUT_Condition();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.FetchImpl <em>Fetch</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.FetchImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getFetch()
     * @generated
     */
    EClass FETCH = eINSTANCE.getFetch();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FETCH__SOURCE = eINSTANCE.getFetch_Source();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FETCH__VALUE = eINSTANCE.getFetch_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FETCH__CONDITION = eINSTANCE.getFetch_Condition();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.CallprocessImpl <em>Callprocess</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.CallprocessImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getCallprocess()
     * @generated
     */
    EClass CALLPROCESS = eINSTANCE.getCallprocess();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALLPROCESS__TARGET = eINSTANCE.getCallprocess_Target();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALLPROCESS__SOURCE = eINSTANCE.getCallprocess_Source();

    /**
     * The meta object literal for the '<em><b>Datasource</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALLPROCESS__DATASOURCE = eINSTANCE.getCallprocess_Datasource();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALLPROCESS__VALUE = eINSTANCE.getCallprocess_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CALLPROCESS__CONDITION = eINSTANCE.getCallprocess_Condition();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.UpdatedauditImpl <em>Updatedaudit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.UpdatedauditImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getUpdatedaudit()
     * @generated
     */
    EClass UPDATEDAUDIT = eINSTANCE.getUpdatedaudit();

    /**
     * The meta object literal for the '<em><b>Logsink</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UPDATEDAUDIT__LOGSINK = eINSTANCE.getUpdatedaudit_Logsink();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UPDATEDAUDIT__VALUE = eINSTANCE.getUpdatedaudit_Value();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.SmsImpl <em>Sms</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.SmsImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getSms()
     * @generated
     */
    EClass SMS = eINSTANCE.getSms();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMS__TARGET = eINSTANCE.getSms_Target();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMS__VALUE = eINSTANCE.getSms_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMS__CONDITION = eINSTANCE.getSms_Condition();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.SlackPUTImpl <em>Slack PUT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.SlackPUTImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getSlackPUT()
     * @generated
     */
    EClass SLACK_PUT = eINSTANCE.getSlackPUT();

    /**
     * The meta object literal for the '<em><b>Team</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SLACK_PUT__TEAM = eINSTANCE.getSlackPUT_Team();

    /**
     * The meta object literal for the '<em><b>Channel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SLACK_PUT__CHANNEL = eINSTANCE.getSlackPUT_Channel();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SLACK_PUT__VALUE = eINSTANCE.getSlackPUT_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SLACK_PUT__CONDITION = eINSTANCE.getSlackPUT_Condition();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.GooglecalPUTImpl <em>Googlecal PUT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.GooglecalPUTImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getGooglecalPUT()
     * @generated
     */
    EClass GOOGLECAL_PUT = eINSTANCE.getGooglecalPUT();

    /**
     * The meta object literal for the '<em><b>Authstore</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOOGLECAL_PUT__AUTHSTORE = eINSTANCE.getGooglecalPUT_Authstore();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOOGLECAL_PUT__KEY = eINSTANCE.getGooglecalPUT_Key();

    /**
     * The meta object literal for the '<em><b>Useraccount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOOGLECAL_PUT__USERACCOUNT = eINSTANCE.getGooglecalPUT_Useraccount();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOOGLECAL_PUT__SOURCE = eINSTANCE.getGooglecalPUT_Source();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOOGLECAL_PUT__VALUE = eINSTANCE.getGooglecalPUT_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOOGLECAL_PUT__CONDITION = eINSTANCE.getGooglecalPUT_Condition();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.CopydataImpl <em>Copydata</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.CopydataImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getCopydata()
     * @generated
     */
    EClass COPYDATA = eINSTANCE.getCopydata();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COPYDATA__SOURCE = eINSTANCE.getCopydata_Source();

    /**
     * The meta object literal for the '<em><b>To</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COPYDATA__TO = eINSTANCE.getCopydata_To();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COPYDATA__VALUE = eINSTANCE.getCopydata_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COPYDATA__CONDITION = eINSTANCE.getCopydata_Condition();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.WriteCsvImpl <em>Write Csv</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.WriteCsvImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getWriteCsv()
     * @generated
     */
    EClass WRITE_CSV = eINSTANCE.getWriteCsv();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_CSV__SOURCE = eINSTANCE.getWriteCsv_Source();

    /**
     * The meta object literal for the '<em><b>To</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_CSV__TO = eINSTANCE.getWriteCsv_To();

    /**
     * The meta object literal for the '<em><b>Delim</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_CSV__DELIM = eINSTANCE.getWriteCsv_Delim();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_CSV__VALUE = eINSTANCE.getWriteCsv_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE_CSV__CONDITION = eINSTANCE.getWriteCsv_Condition();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.LoadCsvImpl <em>Load Csv</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.LoadCsvImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getLoadCsv()
     * @generated
     */
    EClass LOAD_CSV = eINSTANCE.getLoadCsv();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_CSV__SOURCE = eINSTANCE.getLoadCsv_Source();

    /**
     * The meta object literal for the '<em><b>To</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_CSV__TO = eINSTANCE.getLoadCsv_To();

    /**
     * The meta object literal for the '<em><b>Delim</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_CSV__DELIM = eINSTANCE.getLoadCsv_Delim();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_CSV__VALUE = eINSTANCE.getLoadCsv_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD_CSV__CONDITION = eINSTANCE.getLoadCsv_Condition();

    /**
     * The meta object literal for the '{@link org.etl.sparrow.impl.TransformImpl <em>Transform</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.etl.sparrow.impl.TransformImpl
     * @see org.etl.sparrow.impl.SparrowPackageImpl#getTransform()
     * @generated
     */
    EClass TRANSFORM = eINSTANCE.getTransform();

    /**
     * The meta object literal for the '<em><b>On</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSFORM__ON = eINSTANCE.getTransform_On();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSFORM__VALUE = eINSTANCE.getTransform_Value();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSFORM__CONDITION = eINSTANCE.getTransform_Condition();

  }

} //SparrowPackage
