/**
 * generated by Xtext 2.12.0
 */
package org.etl.sparrow;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.etl.sparrow.SparrowPackage
 * @generated
 */
public interface SparrowFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SparrowFactory eINSTANCE = org.etl.sparrow.impl.SparrowFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Process</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Process</em>'.
   * @generated
   */
  Process createProcess();

  /**
   * Returns a new object of class '<em>Try</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Try</em>'.
   * @generated
   */
  Try createTry();

  /**
   * Returns a new object of class '<em>Finally</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Finally</em>'.
   * @generated
   */
  Finally createFinally();

  /**
   * Returns a new object of class '<em>Catch</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Catch</em>'.
   * @generated
   */
  Catch createCatch();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Callprocess</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Callprocess</em>'.
   * @generated
   */
  Callprocess createCallprocess();

  /**
   * Returns a new object of class '<em>Updatedaudit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Updatedaudit</em>'.
   * @generated
   */
  Updatedaudit createUpdatedaudit();

  /**
   * Returns a new object of class '<em>Sms</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sms</em>'.
   * @generated
   */
  Sms createSms();

  /**
   * Returns a new object of class '<em>Slack</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Slack</em>'.
   * @generated
   */
  Slack createSlack();

  /**
   * Returns a new object of class '<em>Googlecal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Googlecal</em>'.
   * @generated
   */
  Googlecal createGooglecal();

  /**
   * Returns a new object of class '<em>Copydata</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Copydata</em>'.
   * @generated
   */
  Copydata createCopydata();

  /**
   * Returns a new object of class '<em>Write Csv</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Write Csv</em>'.
   * @generated
   */
  WriteCsv createWriteCsv();

  /**
   * Returns a new object of class '<em>Load Csv</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Load Csv</em>'.
   * @generated
   */
  LoadCsv createLoadCsv();

  /**
   * Returns a new object of class '<em>Transform</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transform</em>'.
   * @generated
   */
  Transform createTransform();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SparrowPackage getSparrowPackage();

} //SparrowFactory
