/**
 * generated by Xtext 2.11.0
 */
package org.etl.sparrow;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trello GET</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.etl.sparrow.TrelloGET#getAuthtoken <em>Authtoken</em>}</li>
 *   <li>{@link org.etl.sparrow.TrelloGET#getKey <em>Key</em>}</li>
 *   <li>{@link org.etl.sparrow.TrelloGET#getUseraccount <em>Useraccount</em>}</li>
 *   <li>{@link org.etl.sparrow.TrelloGET#getBoard <em>Board</em>}</li>
 *   <li>{@link org.etl.sparrow.TrelloGET#getTarget <em>Target</em>}</li>
 *   <li>{@link org.etl.sparrow.TrelloGET#getValue <em>Value</em>}</li>
 *   <li>{@link org.etl.sparrow.TrelloGET#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see org.etl.sparrow.SparrowPackage#getTrelloGET()
 * @model
 * @generated
 */
public interface TrelloGET extends Action
{
  /**
   * Returns the value of the '<em><b>Authtoken</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Authtoken</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Authtoken</em>' attribute.
   * @see #setAuthtoken(String)
   * @see org.etl.sparrow.SparrowPackage#getTrelloGET_Authtoken()
   * @model
   * @generated
   */
  String getAuthtoken();

  /**
   * Sets the value of the '{@link org.etl.sparrow.TrelloGET#getAuthtoken <em>Authtoken</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Authtoken</em>' attribute.
   * @see #getAuthtoken()
   * @generated
   */
  void setAuthtoken(String value);

  /**
   * Returns the value of the '<em><b>Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key</em>' attribute.
   * @see #setKey(String)
   * @see org.etl.sparrow.SparrowPackage#getTrelloGET_Key()
   * @model
   * @generated
   */
  String getKey();

  /**
   * Sets the value of the '{@link org.etl.sparrow.TrelloGET#getKey <em>Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key</em>' attribute.
   * @see #getKey()
   * @generated
   */
  void setKey(String value);

  /**
   * Returns the value of the '<em><b>Useraccount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Useraccount</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Useraccount</em>' attribute.
   * @see #setUseraccount(String)
   * @see org.etl.sparrow.SparrowPackage#getTrelloGET_Useraccount()
   * @model
   * @generated
   */
  String getUseraccount();

  /**
   * Sets the value of the '{@link org.etl.sparrow.TrelloGET#getUseraccount <em>Useraccount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Useraccount</em>' attribute.
   * @see #getUseraccount()
   * @generated
   */
  void setUseraccount(String value);

  /**
   * Returns the value of the '<em><b>Board</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Board</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Board</em>' attribute.
   * @see #setBoard(String)
   * @see org.etl.sparrow.SparrowPackage#getTrelloGET_Board()
   * @model
   * @generated
   */
  String getBoard();

  /**
   * Sets the value of the '{@link org.etl.sparrow.TrelloGET#getBoard <em>Board</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Board</em>' attribute.
   * @see #getBoard()
   * @generated
   */
  void setBoard(String value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see org.etl.sparrow.SparrowPackage#getTrelloGET_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link org.etl.sparrow.TrelloGET#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.etl.sparrow.SparrowPackage#getTrelloGET_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.etl.sparrow.TrelloGET#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see org.etl.sparrow.SparrowPackage#getTrelloGET_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link org.etl.sparrow.TrelloGET#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

} // TrelloGET
